- by removing @Size(max = 30) validation on BeerDTO
- I am allowing the JPA to throw its validation errors

- i.e. the validation checking occurs via @Size(max = 30) and @Column(length = 30) annotations on the Beer entity objects

- this results in the following exception stacks:

jakarta.servlet.ServletException: Request processing failed: org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction

Caused by: org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction

Caused by: jakarta.persistence.RollbackException: Error while committing the transaction
	at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:83)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)

Caused by: jakarta.validation.ConstraintViolationException: Validation failed for classes [guru.springframework.spring6restmvc.entities.Beer] during update time for groups [jakarta.validation.groups.Default, ]